import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Home({ sheetdata }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {sheetdata &&
        sheetdata.map(e => <h1 key={e[0]}>{e[1]}</h1>)
        
        }
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const req = await fetch("http://localhost:3001/api/client");
  const res = await req.json();
  return {
    props: {
      sheetdata: res.data,
    },
  };
}
